In [6]:

import re
import json
import csv
import requests
from bs4 import BeautifulSoup ,SoupStrainer
import pandas as pd 
from io import StringIO


from selenium import webdriver
import time

In [20]:
###############################################################################################

#getting Historical data page"
headers = { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' }

Main_url ='https://finance.yahoo.com/quote/NDAQ?p=NDAQ&.tsrc=fin-srch'
r = requests.get(Main_url)
soup = BeautifulSoup( r.content , 'html.parser')

for name in soup.find_all('ul',attrs = {"class": "List(n) Whs(nw) fin-tab-items W(100%) Lh(1.7) H(44px) Bdbs(s) BdB(4px) Cf Mb(15px) Bdbc($seperatorColor)" }):
    for link in name.find_all('a', text = "Historical Data"): 
        links = link.get('href')
Hiso_URL = "https://finance.yahoo.com" + links 
print(Hiso_URL)

https://finance.yahoo.com/quote/NDAQ/history?p=NDAQ

In [22]:
for name in soup.find_all('div',attrs = {"class": "C($tertiaryColor) Mt(20px) Mb(15px)"}):
    print(lin)

In [13]:
#Getting to Dta

resp = requests.get(Hiso_URL, headers=headers, timeout=5)
soup1 = BeautifulSoup(resp.content , 'html.parser')

for name in soup1.find_all('div',attrs = {"class": "C($tertiaryColor) Mt(20px) Mb(15px)"}):
    lin = name.get('href')
    
print(lin)
  #--------------------------#
link = 'https://query1.finance.yahoo.com/v7/finance/download/NDAQ?period1=1025481600&period2=1651104000&interval=1d&events=history&includeAdjustedClose=true'
            #Need to figure out why link is not there
link = 'https://query1.finance.yahoo.com/v7/finance/download/%5ERUT?period1=558230400&period2=1651104000&interval=1d&events=history&includeAdjustedClose=true'    
#link = 'https://query1.finance.yahoo.com/v7/finance/download/NDAQ{}?'

#response = requests.get(link , headers=headers, timeout=5)

#params = {

#'period1': '%s' %int(past_date.timestamp()),
#'period2': '%s' %int(dt.timestamp()),
#'events': 'history',
#'includeAdjustedClose': 'true'

#}

#response = requests.get(link , params = params ,headers=headers, timeout=5)

response = requests.get(link , headers=headers, timeout=5)

file = StringIO(response.text)
reader =csv.reader(file)
df = pd.read_csv(file)

None

In [4]:
df.drop(["Volume","Adj Close"], axis=1, inplace=True)

NameError: name 'df' is not defined

In [292]:
df['Dayly change'] = (df['Close']-df['Open'])/df['Open']*100
df['Dayly change Max'] =  abs((df['High']-df['Low'])/df['Low']*100)

In [293]:
df

,Date,Open,High,Low,Close,Dayly change,Dayly change Max
0,1987-09-10,167.440002,168.979996,167.440002,168.970001,0.913760,0.919729
1,1987-09-11,168.970001,170.539993,168.750000,170.539993,0.929154,1.060737
2,1987-09-14,170.529999,170.949997,170.149994,170.429993,-0.058644,0.470175
3,1987-09-15,170.419998,170.440002,169.130005,169.199997,-0.715879,0.774550
4,1987-09-16,169.309998,170.029999,168.820007,168.919998,-0.230347,0.716735
...,...,...,...,...,...,...,...
8723,2022-04-21,2046.709961,2060.080078,1986.910034,1991.459961,-2.699454,3.682605
8724,2022-04-22,1986.660034,1986.660034,1939.339966,1940.660034,-2.315444,2.440009
8725,2022-04-25,1933.239990,1954.400024,1908.819946,1954.199951,1.084188,2.387867
8726,2022-04-26,1940.079956,1940.079956,1890.469971,1890.469971,-2.557110,2.624214
8727,2022-04-27,1891.109985,1909.109985,1879.650024,1884.040039,-0.373852,1.567311